# Generated by Django 5.0.2 on 2024-03-07 10:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_start_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('event_organiser_email', models.EmailField(max_length=254)),
                ('event_organiser_name', models.CharField(max_length=100)),
                ('google_event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('eventorganizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('club_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('profileline', models.CharField(max_length=200)),
                ('imageaddress', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('musician_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profileline', models.CharField(max_length=200)),
                ('imageAddress', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('UserCredential_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
