# Generated by Django 5.0.2 on 2024-03-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('form_filling_date', models.DateField()),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('attendees_gmail', models.EmailField(max_length=254)),
                ('event_organiser_email', models.EmailField(max_length=254)),
                ('event_organiser_name', models.CharField(max_length=100)),
            ],
        ),
    ]
