# Generated by Django 5.0.2 on 2024-03-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_alter_usercredentials_usercredential_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
