# Generated by Django 5.0.2 on 2024-03-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_alter_eventorganizer_email_alter_musician_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_organiser_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
